### ISSUE TITLE
Pin dependency version in pyproject.toml

### ISSUE THREAD

**Issue by almoehi** [bagjohn/larvaworld_autoversioning#4]
Currently all dependencies use * which means "any version is ok". This can lead to incompatible dependencies being used and crash larvaworld.

We should pin the versions that are required to run larvaworld appropriately

Probably using the tilde modifier:

~1.2 	>=1.2.0 <1.3.0

**Comment by bagjohn** [comment]
All dependencies pinned as pkg=x.x.*

Thx almoehi!
